# Generated by Django 4.0.4 on 2022-05-30 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='share_conter',
            new_name='share_counter',
        ),
    ]
